// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1aME2hY4gFF3gdkp17ZewVK8Ecdcn9cY',
    appId: '1:160295799677:web:28a04debe10801a3685a14',
    messagingSenderId: '160295799677',
    projectId: 'zynth-ovlo-tracker',
    authDomain: 'zynth-ovlo-tracker.firebaseapp.com',
    storageBucket: 'zynth-ovlo-tracker.firebasestorage.app',
    measurementId: 'G-KFEVZL0KNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74oNqK65wbBivan7bL44czv0bfNwE_II',
    appId: '1:160295799677:android:64a5591f6a177529685a14',
    messagingSenderId: '160295799677',
    projectId: 'zynth-ovlo-tracker',
    storageBucket: 'zynth-ovlo-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOUDI38m81dRfkTwW4FaWadCHhk1SETA',
    appId: '1:160295799677:ios:3261c64da0f7ac69685a14',
    messagingSenderId: '160295799677',
    projectId: 'zynth-ovlo-tracker',
    storageBucket: 'zynth-ovlo-tracker.firebasestorage.app',
    iosClientId: '160295799677-5cqf3p982j4gonvgr7gad3t9kgcr7gnp.apps.googleusercontent.com',
    iosBundleId: 'com.zynth.ovlotracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOUDI38m81dRfkTwW4FaWadCHhk1SETA',
    appId: '1:160295799677:ios:071876f3720f2214685a14',
    messagingSenderId: '160295799677',
    projectId: 'zynth-ovlo-tracker',
    storageBucket: 'zynth-ovlo-tracker.firebasestorage.app',
    iosClientId: '160295799677-61t1ifujib6mghos5gfsk3hpqrkmomj3.apps.googleusercontent.com',
    iosBundleId: 'com.zynth.trackher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1aME2hY4gFF3gdkp17ZewVK8Ecdcn9cY',
    appId: '1:160295799677:web:02904b74773e73c8685a14',
    messagingSenderId: '160295799677',
    projectId: 'zynth-ovlo-tracker',
    authDomain: 'zynth-ovlo-tracker.firebaseapp.com',
    storageBucket: 'zynth-ovlo-tracker.firebasestorage.app',
    measurementId: 'G-2RPWZ29FET',
  );
}
